# Generated by Django 3.2 on 2022-03-07 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pick_date', models.DateField()),
                ('pick_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TableInverntory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tablecount', models.IntegerField(default=20)),
                ('Tables_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='newbookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.newbooking')),
            ],
        ),
    ]
