# Generated by Django 3.2 on 2022-03-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooktable',
            name='Booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='bookings.newbooking'),
        ),
    ]
