# Generated by Django 3.2 on 2022-03-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_newbooktable_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooktable',
            name='Booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='bookings.newbooking'),
        ),
    ]
